name: ci

on:
  pull_request:
  push:
    branches: master

jobs:
  build:
    name: Build and test

    strategy:
      matrix:
        lua-version: ["5.4", "5.3", "5.2", "5.1", "luajit"]
        os: ["ubuntu-latest"]
        include:
        - os: "macos-latest"
          lua-version: "5.4"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master

    - name: Install Package
      uses: ConorMacBride/install-package@v1.1.0
      with:
        brew: libev
        apt: libev-dev
        choco: libev

    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.lua-version }}

    - uses: hishamhm/gh-actions-luarocks@master

    - name: Build
      run: |
        luarocks make --only-deps

    - name: Test
      run: |
        luarocks lint expect-promise-1.0-1.rockspec
        luarocks test